// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Luiu.Domain.Models;

public partial class LuiuDbContext : DbContext
{
    public LuiuDbContext(DbContextOptions<LuiuDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TAdminLog> TAdminLogs { get; set; }

    public virtual DbSet<TCategory> TCategories { get; set; }

    public virtual DbSet<TCollect> TCollects { get; set; }

    public virtual DbSet<TComment> TComments { get; set; }

    public virtual DbSet<TCommentLike> TCommentLikes { get; set; }

    public virtual DbSet<TEvent> TEvents { get; set; }

    public virtual DbSet<TEventRank> TEventRanks { get; set; }

    public virtual DbSet<TEventSpotRelation> TEventSpotRelations { get; set; }

    public virtual DbSet<TEventTagRelation> TEventTagRelations { get; set; }

    public virtual DbSet<TExpense> TExpenses { get; set; }

    public virtual DbSet<TExpensesSplit> TExpensesSplits { get; set; }

    public virtual DbSet<TFollow> TFollows { get; set; }

    public virtual DbSet<TLoginLog> TLoginLogs { get; set; }

    public virtual DbSet<TMember> TMembers { get; set; }

    public virtual DbSet<TMemory> TMemories { get; set; }

    public virtual DbSet<TMemoryDay> TMemoryDays { get; set; }

    public virtual DbSet<TMemoryStop> TMemoryStops { get; set; }

    public virtual DbSet<TOauthLogin> TOauthLogins { get; set; }

    public virtual DbSet<TPackingCategory> TPackingCategories { get; set; }

    public virtual DbSet<TPackingItem> TPackingItems { get; set; }

    public virtual DbSet<TPost> TPosts { get; set; }

    public virtual DbSet<TPostLike> TPostLikes { get; set; }

    public virtual DbSet<TPostTag> TPostTags { get; set; }

    public virtual DbSet<TReference> TReferences { get; set; }

    public virtual DbSet<TRegion> TRegions { get; set; }

    public virtual DbSet<TRegionRank> TRegionRanks { get; set; }

    public virtual DbSet<TReport> TReports { get; set; }

    public virtual DbSet<TRole> TRoles { get; set; }

    public virtual DbSet<TSpot> TSpots { get; set; }

    public virtual DbSet<TSpotMonthlySnap> TSpotMonthlySnaps { get; set; }

    public virtual DbSet<TSpotRank> TSpotRanks { get; set; }

    public virtual DbSet<TSpotTagRelation> TSpotTagRelations { get; set; }

    public virtual DbSet<TSpotType> TSpotTypes { get; set; }

    public virtual DbSet<TSpotTypeRelation> TSpotTypeRelations { get; set; }

    public virtual DbSet<TSystemConfig> TSystemConfigs { get; set; }

    public virtual DbSet<TSystemLog> TSystemLogs { get; set; }

    public virtual DbSet<TTag> TTags { get; set; }

    public virtual DbSet<TTrip> TTrips { get; set; }

    public virtual DbSet<TTripCollaborator> TTripCollaborators { get; set; }

    public virtual DbSet<TTripComment> TTripComments { get; set; }

    public virtual DbSet<TTripDetail> TTripDetails { get; set; }

    public virtual DbSet<TTripSuggest> TTripSuggests { get; set; }

    public virtual DbSet<TType> TTypes { get; set; }

    public virtual DbSet<TUserPackingList> TUserPackingLists { get; set; }

    public virtual DbSet<TVerification> TVerifications { get; set; }

    public virtual DbSet<TViolationRule> TViolationRules { get; set; }

    public virtual DbSet<TRouteCache> TRouteCaches { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TAdminLog>(entity =>
        {
            entity.HasKey(e => e.ActionId).HasName("PK_AdminLogs");

            entity.ToTable("tAdminLogs");

            entity.Property(e => e.ActionId).HasColumnName("ActionID");
            entity.Property(e => e.ActionReason)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ActionTime)
                .HasDefaultValueSql("getdate()", "DF_AdminLogs_ActionTime")
                .HasColumnType("datetime");
            entity.Property(e => e.ActionType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.AdminId).HasColumnName("AdminID");
            entity.Property(e => e.IpAddress)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PenaltyTime).HasColumnType("datetime");
            entity.Property(e => e.ReportId).HasColumnName("ReportID");
            entity.Property(e => e.TargetId).HasColumnName("TargetID");
            entity.Property(e => e.TargetType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId);

            entity.ToTable("tCategories");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TCollect>(entity =>
        {
            entity.HasKey(e => e.CollectId).HasName("PK_Collects");

            entity.ToTable("tCollects");

            entity.Property(e => e.CollectId).HasColumnName("CollectID");
            entity.Property(e => e.CollectTime).HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.ObjectId).HasColumnName("ObjectID");
            entity.Property(e => e.TypeId).HasColumnName("TypeID");
        });

        modelBuilder.Entity<TComment>(entity =>
        {
            entity.HasKey(e => e.CommentId);

            entity.ToTable("tComments");

            entity.Property(e => e.CommentId).HasColumnName("CommentID");
            entity.Property(e => e.CommentContent)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CommentTime)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.PostId).HasColumnName("PostID");
        });

        modelBuilder.Entity<TCommentLike>(entity =>
        {
            entity.HasKey(e => e.CommentLikeId);

            entity.ToTable("tCommentLikes");

            entity.Property(e => e.CommentLikeId).HasColumnName("CommentLikeID");
            entity.Property(e => e.CommentId).HasColumnName("CommentID");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
        });

        modelBuilder.Entity<TEvent>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK_Event");

            entity.ToTable("tEvents");

            entity.Property(e => e.EventId).HasColumnName("EventID");
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("getdate()", "DF_Event_CreateTime")
                .HasColumnType("datetime");
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.EventName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.EventType).HasMaxLength(50);
            entity.Property(e => e.ImageBg).HasColumnName("ImageBG");
            entity.Property(e => e.OfficialUrl).HasColumnName("OfficialURL");
            entity.Property(e => e.StartTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<TEventRank>(entity =>
        {
            entity.HasKey(e => e.EventRankId).HasName("PK_EventRank");

            entity.ToTable("tEventRanks");

            entity.Property(e => e.EventRankId).HasColumnName("EventRankID");
            entity.Property(e => e.EventId).HasColumnName("EventID");
            entity.Property(e => e.EventName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RankDate)
                .HasDefaultValueSql("getdate()", "DF_EventRank_RankDate")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TEventSpotRelation>(entity =>
        {
            entity.HasKey(e => new { e.EventId, e.SpotId }).HasName("PK_EventSpotRelation");

            entity.ToTable("tEventSpotRelations");

            entity.Property(e => e.EventId).HasColumnName("EventID");
            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
        });

        modelBuilder.Entity<TEventTagRelation>(entity =>
        {
            entity.HasKey(e => new { e.EventId, e.TagId }).HasName("PK_EventTagRelation");

            entity.ToTable("tEventTagRelations");

            entity.Property(e => e.EventId).HasColumnName("EventID");
            entity.Property(e => e.TagId).HasColumnName("TagID");
        });

        modelBuilder.Entity<TExpense>(entity =>
        {
            entity.HasKey(e => e.ExpenseId);

            entity.ToTable("tExpenses");

            entity.Property(e => e.ExpenseId).HasColumnName("ExpenseID");
            entity.Property(e => e.MemoryId).HasColumnName("MemoryID");
            entity.Property(e => e.PayerUserId).HasColumnName("PayerUserID");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<TExpensesSplit>(entity =>
        {
            entity.HasKey(e => e.SplitId);

            entity.ToTable("tExpensesSplits");

            entity.Property(e => e.SplitId).HasColumnName("SplitID");
            entity.Property(e => e.DebtorUserId).HasColumnName("DebtorUserID");
            entity.Property(e => e.ExpenseId).HasColumnName("ExpenseID");
            entity.Property(e => e.OweAmount).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<TFollow>(entity =>
        {
            entity.HasKey(e => new { e.FollowerId, e.FollowingId }).HasName("PK_Follows");

            entity.ToTable("tFollows");

            entity.Property(e => e.FollowerId).HasColumnName("FollowerID");
            entity.Property(e => e.FollowingId).HasColumnName("FollowingID");
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("getdate()", "DF_Follows_CreateTime")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TLoginLog>(entity =>
        {
            entity.HasKey(e => e.LoginId).HasName("PK_LoginLogs");

            entity.ToTable("tLoginLogs");

            entity.Property(e => e.LoginId).HasColumnName("LoginID");
            entity.Property(e => e.DeviceInfo).IsRequired();
            entity.Property(e => e.FailureReason)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Ipaddress)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("IPAddress");
            entity.Property(e => e.Location).HasMaxLength(100);
            entity.Property(e => e.LoginTime)
                .HasDefaultValueSql("getdate()", "DF_LoginLogs_LoginTime")
                .HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TMember>(entity =>
        {
            entity.HasKey(e => e.MemberId).HasName("PK_Members");

            entity.ToTable("tMembers");

            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.AvatarUrl).HasMaxLength(255);
            entity.Property(e => e.Bio).HasMaxLength(200);
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.DeleteTime).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.LockReason).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("UserID");
        });

        modelBuilder.Entity<TMemory>(entity =>
        {
            entity.HasKey(e => e.MemoryId);

            entity.ToTable("tMemories");

            entity.Property(e => e.MemoryId).HasColumnName("MemoryID");
            entity.Property(e => e.CoverImage).HasMaxLength(255);
            entity.Property(e => e.OfficeOper).HasDefaultValue((short)0);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UserId).HasColumnName("UserID");
            entity.Property(e => e.IsDelete).HasDefaultValue(false);
        });

        modelBuilder.Entity<TMemoryDay>(entity =>
        {
            entity.HasKey(e => e.DayId);

            entity.ToTable("tMemoryDays");

            entity.Property(e => e.DayId).HasColumnName("DayID");
            entity.Property(e => e.MemoryId).HasColumnName("MemoryID");
        });

        modelBuilder.Entity<TMemoryStop>(entity =>
        {
            entity.HasKey(e => e.StopId);

            entity.ToTable("tMemoryStops");

            entity.Property(e => e.StopId).HasColumnName("StopID");
            entity.Property(e => e.DayId).HasColumnName("DayID");
            entity.Property(e => e.Duration).HasMaxLength(50);
            entity.Property(e => e.Expense).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.Latitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.PlaceName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.VideoEmbedUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("VideoEmbedURL");
        });

        modelBuilder.Entity<TOauthLogin>(entity =>
        {
            entity.HasKey(e => new { e.AuthType, e.ProviderKey }).HasName("PK_OAuthLogin");

            entity.ToTable("tOAuthLogins");

            entity.Property(e => e.AuthType)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ProviderKey).HasMaxLength(255);
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("getdate()", "DF_OAuthLogin_CreateTime")
                .HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.ProviderDisplayName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TPackingCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId);

            entity.ToTable("tPackingCategories");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.ListId).HasColumnName("ListID");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TPackingItem>(entity =>
        {
            entity.HasKey(e => e.ItemId);

            entity.ToTable("tPackingItems");

            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.IsCheck).HasDefaultValue(false);
            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TPost>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("PK__Posts__AA12603828164C07");

            entity.ToTable("tPosts");

            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.PostContent)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.PostTime)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.PostTitle)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ReferenceId).HasColumnName("ReferenceID");
        });

        modelBuilder.Entity<TPostLike>(entity =>
        {
            entity.HasKey(e => e.PostLikeId);

            entity.ToTable("tPostLikes");

            entity.Property(e => e.PostLikeId).HasColumnName("PostLikeID");
            entity.Property(e => e.LikeTime)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.PostId).HasColumnName("PostID");
        });

        modelBuilder.Entity<TPostTag>(entity =>
        {
            entity.HasKey(e => e.PostTagId);

            entity.ToTable("tPostTags");

            entity.Property(e => e.PostTagId).HasColumnName("PostTagID");
            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.TagId).HasColumnName("TagID");
        });

        modelBuilder.Entity<TReference>(entity =>
        {
            entity.HasKey(e => e.ReferenceId);

            entity.ToTable("tReferences");

            entity.Property(e => e.ReferenceId).HasColumnName("ReferenceID");
            entity.Property(e => e.ReferenceItemId).HasColumnName("ReferenceItemID");
            entity.Property(e => e.TypeId).HasColumnName("TypeID");
        });

        modelBuilder.Entity<TRegion>(entity =>
        {
            entity.HasKey(e => e.RegionId).HasName("PK_SpotRegion");

            entity.ToTable("tRegions");

            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.RegionName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TRegionRank>(entity =>
        {
            entity.HasKey(e => e.RegionRankId).HasName("PK_RegionRanks");

            entity.ToTable("tRegionRanks");

            entity.Property(e => e.RegionRankId).HasColumnName("RegionRankID");
            entity.Property(e => e.RankDate)
                .HasDefaultValueSql("getdate()", "DF_RegionRank_RankDate")
                .HasColumnType("datetime");
            entity.Property(e => e.RankType).HasMaxLength(50);
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.RegionName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TReport>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK_Reports");

            entity.ToTable("tReports");

            entity.Property(e => e.ReportId).HasColumnName("ReportID");
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("getdate()", "DF_Reports_CreateTime")
                .HasColumnType("datetime");
            entity.Property(e => e.ReportReason)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ReporterId).HasColumnName("ReporterID");
            entity.Property(e => e.RuleId).HasColumnName("RuleID");
            entity.Property(e => e.TargetId).HasColumnName("TargetID");
            entity.Property(e => e.TargetType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TRole>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK_Role");

            entity.ToTable("tRole");

            entity.Property(e => e.RoleId)
                .ValueGeneratedNever()
                .HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<TSpot>(entity =>
        {
            entity.HasKey(e => e.SpotId).HasName("PK_Spot");

            entity.ToTable("tSpots");

            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.GoogleMapId).HasColumnName("GoogleMapID");
            entity.Property(e => e.GoogleMapUrl).HasColumnName("GoogleMapURL");
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.Latitude).HasColumnType("decimal(10, 8)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(11, 8)");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.OfficialUrl).HasColumnName("OfficialURL");
            entity.Property(e => e.PhotoReference).HasMaxLength(512);
            entity.Property(e => e.PriceLevel).HasMaxLength(50);
            entity.Property(e => e.Rating).HasColumnType("decimal(2, 1)");
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.SpotName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Tel).HasMaxLength(50);
        });

        modelBuilder.Entity<TSpotMonthlySnap>(entity =>
        {
            entity.HasKey(e => e.SnapId).HasName("PK_SpotMonthlySnap");

            entity.ToTable("tSpotMonthlySnaps");

            entity.Property(e => e.SnapId).HasColumnName("SnapID");
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.SnapTime)
                .HasDefaultValueSql("getdate()", "DF_SpotMonthlySnap_SnapTime")
                .HasColumnType("datetime");
            entity.Property(e => e.SpotId).HasColumnName("SpotID");
        });

        modelBuilder.Entity<TSpotRank>(entity =>
        {
            entity.HasKey(e => e.SpotRankId).HasName("PK_SpotRank");

            entity.ToTable("tSpotRanks");

            entity.Property(e => e.SpotRankId).HasColumnName("SpotRankID");
            entity.Property(e => e.RankDate)
                .HasDefaultValueSql("getdate()", "DF_SpotRank_RankDate")
                .HasColumnType("datetime");
            entity.Property(e => e.RankType).HasMaxLength(50);
            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.SpotName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TSpotTagRelation>(entity =>
        {
            entity.HasKey(e => new { e.SpotId, e.SpotTagId }).HasName("PK_SpotTagRelation");

            entity.ToTable("tSpotTagRelations");

            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.SpotTagId).HasColumnName("SpotTagID");
        });

        modelBuilder.Entity<TSpotType>(entity =>
        {
            entity.HasKey(e => e.TypeId).HasName("PK_SpotType_1");

            entity.ToTable("tSpotTypes");

            entity.Property(e => e.TypeId).HasColumnName("TypeID");
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TSpotTypeRelation>(entity =>
        {
            entity.HasKey(e => new { e.SpotId, e.TypeId }).HasName("PK_SpotType");

            entity.ToTable("tSpotTypeRelations");

            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.TypeId).HasColumnName("TypeID");
        });

        modelBuilder.Entity<TSystemConfig>(entity =>
        {
            entity.HasKey(e => e.ConfigKey).HasName("PK_SystemConfig");

            entity.ToTable("tSystemConfigs");

            entity.Property(e => e.ConfigKey).HasMaxLength(50);
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("getdate()", "DF_SystemConfig_LastUpdated")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TSystemLog>(entity =>
        {
            entity.ToTable("tSystemLogs");

            entity.Property(e => e.Developer).HasMaxLength(50);
            entity.Property(e => e.Level).HasMaxLength(16);
            entity.Property(e => e.Source).HasMaxLength(50);
            entity.Property(e => e.TimeStamp).HasColumnType("datetime");
        });

        modelBuilder.Entity<TTag>(entity =>
        {
            entity.HasKey(e => e.TagId);

            entity.ToTable("tTags");

            entity.Property(e => e.TagId).HasColumnName("TagID");
            entity.Property(e => e.TagName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TTrip>(entity =>
        {
            entity.HasKey(e => e.TripId);

            entity.ToTable("tTrips");

            entity.Property(e => e.TripId).HasColumnName("TripID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.IsSuggest).HasDefaultValue(false);
            entity.Property(e => e.ListId).HasColumnName("ListID");
            entity.Property(e => e.OfficeOper).HasDefaultValue((short)0);
            entity.Property(e => e.OwnerId).HasColumnName("OwnerID");
            entity.Property(e => e.PhotoUrl).HasColumnName("PhotoURL");
            entity.Property(e => e.PrivacyStatus).HasDefaultValue((byte)0);
            entity.Property(e => e.ShortCode).HasMaxLength(8);
            entity.Property(e => e.TripDesc).HasMaxLength(50);
            entity.Property(e => e.TripGuid).HasDefaultValueSql("newid()");
            entity.Property(e => e.TripTag).HasMaxLength(10);
            entity.Property(e => e.TripName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TTripCollaborator>(entity =>
        {
            entity.HasKey(e => e.CollaboratorId);

            entity.ToTable("tTripCollaborators");

            entity.Property(e => e.CollaboratorId).HasColumnName("CollaboratorID");
            entity.Property(e => e.Role).HasDefaultValue((byte)0);
            entity.Property(e => e.TripId).HasColumnName("TripID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<TTripComment>(entity =>
        {
            entity.HasKey(e => e.CommentId);

            entity.ToTable("tTripComments");

            entity.Property(e => e.CommentId).HasColumnName("CommentID");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.TripId).HasColumnName("TripID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<TTripDetail>(entity =>
        {
            entity.HasKey(e => e.DetailId);

            entity.ToTable("tTripDetails");

            entity.Property(e => e.DetailId).HasColumnName("DetailID");
            entity.Property(e => e.Budget).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.IsMaster).HasDefaultValue(false);
            entity.Property(e => e.Notes).HasMaxLength(50);
            entity.Property(e => e.PolylineEncoded).HasColumnName("PolylineEncoded");
            entity.Property(e => e.SpotAlias).HasMaxLength(20);
            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.StayDuration).HasDefaultValue((short)60);
            entity.Property(e => e.TripId).HasColumnName("TripID");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.VersionId)
                .HasDefaultValue((byte)0)
                .HasColumnName("VersionID");
        });

        modelBuilder.Entity<TTripSuggest>(entity =>
        {
            entity.HasKey(e => e.SuggesterId);

            entity.ToTable("tTripSuggests");

            entity.Property(e => e.SuggesterId).HasColumnName("SuggesterID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.IsApproved).HasDefaultValue(false);
            entity.Property(e => e.SuggestByUserId).HasColumnName("SuggestByUserID");
            entity.Property(e => e.Summary).HasMaxLength(100);
            entity.Property(e => e.TripId).HasColumnName("TripID");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.VersionName)
                .IsRequired()
                .HasMaxLength(10);
        });

        modelBuilder.Entity<TType>(entity =>
        {
            entity.HasKey(e => e.TypeId).HasName("PK_Types");

            entity.ToTable("tTypes");

            entity.Property(e => e.TypeId).HasColumnName("TypeID");
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<TUserPackingList>(entity =>
        {
            entity.HasKey(e => e.ListId);

            entity.ToTable("tUserPackingLists");

            entity.Property(e => e.ListId).HasColumnName("ListID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.ListName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<TVerification>(entity =>
        {
            entity.HasKey(e => e.VerificationId).HasName("PK_Verification");

            entity.ToTable("tVerifications");

            entity.Property(e => e.VerificationId).HasColumnName("VerificationID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.RequestIp)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("RequestIP");
            entity.Property(e => e.TokenHash)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TViolationRule>(entity =>
        {
            entity.HasKey(e => e.RuleId).HasName("PK_ViolationRules");

            entity.ToTable("tViolationRules");

            entity.Property(e => e.RuleId).HasColumnName("RuleID");
            entity.Property(e => e.DefaultAction).HasMaxLength(50);
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.IsActivate).HasDefaultValue(true);
            entity.Property(e => e.RuleType)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Severity).HasDefaultValue((byte)3);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("getdate()")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TRouteCache>(entity =>
        {
            entity.HasKey(e => e.CacheID);

            entity.ToTable("tRouteCache");

            entity.HasIndex(e => e.CacheKey).IsUnique();

            entity.Property(e => e.CacheID).HasColumnName("CacheID");
            entity.Property(e => e.CacheKey)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreatedAt).HasColumnType("datetime");
            entity.Property(e => e.ExpiredAt).HasColumnType("datetime");
            entity.Property(e => e.ResultJson).IsRequired();
            entity.Property(e => e.SpotIdsJson).IsRequired();
            entity.Property(e => e.TravelMode)
                .IsRequired()
                .HasMaxLength(20);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
