// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;

namespace Luiu.Domain.Models;

public partial class TDemoSession
{
    public Guid DemoSessionId { get; set; }

    public int MemberId { get; set; }

    public string ClientIpHash { get; set; }

    public string UserAgentHash { get; set; }

    public DateTime StartedAt { get; set; }

    public DateTime ExpiresAt { get; set; }

    public DateTime? EndedAt { get; set; }

    public string EndReason { get; set; }

    public int PlaceSearchCount { get; set; }

    public int RouteComputeCount { get; set; }

    public int RouteExternalLegCount { get; set; }

    public int CreatedTripCount { get; set; }

    public int CreatedCollectCount { get; set; }
}
