// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TEventRank
{
    public int EventRankId { get; set; }

    public int EventId { get; set; }

    public string EventName { get; set; }

    public DateTime RankDate { get; set; }

    public int? Rank { get; set; }
}