// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TExpensesSplit
{
    public int SplitId { get; set; }

    public int ExpenseId { get; set; }

    public int DebtorUserId { get; set; }

    public decimal OweAmount { get; set; }
}