// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TLoginLog
{
    public int LoginId { get; set; }

    public DateTime LoginTime { get; set; }

    public string Ipaddress { get; set; }

    public string Status { get; set; }

    public string Location { get; set; }

    public string DeviceInfo { get; set; }

    public string FailureReason { get; set; }

    public int MemberId { get; set; }
}