// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TMemoryDay
{
    public int DayId { get; set; }

    public int MemoryId { get; set; }

    public int DayNumber { get; set; }

    public DateOnly? DayDate { get; set; }
}