// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TMemory
{
    public int MemoryId { get; set; }

    public int UserId { get; set; }

    public string Title { get; set; }

    public string CoverImage { get; set; }

    public DateOnly? StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public int ReviewStatus { get; set; }

    public int ViewCount { get; set; }

    public int LikeCount { get; set; }

    public int FavoriteCount { get; set; }

    public short? OfficeOper { get; set; }

    public int? SourceTripId { get; set; }

    public bool IsDelete { get; set; }
}