// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TPost
{
    public int PostId { get; set; }

    public int CategoryId { get; set; }

    public string PostTitle { get; set; }

    public int MemberId { get; set; }

    public string PostContent { get; set; }

    public DateTime PostTime { get; set; }

    public bool IsDelete { get; set; }

    public int CommentAmount { get; set; }

    public int ViewCount { get; set; }

    public int? TagAmount { get; set; }

    public int? ReferenceId { get; set; }

    public bool IsEdit { get; set; }
}