// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TRegion
{
    public int RegionId { get; set; }

    public string RegionName { get; set; }
}