// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TReport
{
    public int ReportId { get; set; }

    public string ReportReason { get; set; }

    public byte Status { get; set; }

    public DateTime CreateTime { get; set; }

    public string TargetType { get; set; }

    public int TargetId { get; set; }

    public int ReporterId { get; set; }

    public int RuleId { get; set; }
}