// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TRouteCache
{
    public int CacheID { get; set; }
    public string CacheKey { get; set; } = string.Empty;
    public string SpotIdsJson { get; set; } = string.Empty;
    public string TravelMode { get; set; } = string.Empty;
    public string ResultJson { get; set; } = string.Empty;
    public DateTime CreatedAt { get; set; }
    public DateTime ExpiredAt { get; set; }
}