// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TTrip
{
    public int TripId { get; set; }

    public string TripName { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly EndDate { get; set; }

    public byte? PrivacyStatus { get; set; }

    public bool? IsSuggest { get; set; }

    public Guid? TripGuid { get; set; }

    public string ShortCode { get; set; }

    public int OwnerId { get; set; }

    public int? ListId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public string TripDesc { get; set; }

    public string TripTag { get; set; }

    public string PhotoUrl { get; set; }

    public short? OfficeOper { get; set; }

    public Guid? DemoSessionId { get; set; }
}
