// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TTripCollaborator
{
    public int CollaboratorId { get; set; }

    public byte? Role { get; set; }

    public int UserId { get; set; }

    public int TripId { get; set; }
}