// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TVerification
{
    public int VerificationId { get; set; }

    public byte Type { get; set; }

    public string TokenHash { get; set; }

    public DateTime CreatedAt { get; set; }

    public string RequestIp { get; set; }

    public int Attempts { get; set; }

    public int MemberId { get; set; }

    public byte Status { get; set; }
}