// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Domain.Models;

public partial class TViolationRule
{
    public int RuleId { get; set; }

    public string Title { get; set; }

    public string Description { get; set; }

    public string RuleType { get; set; }

    public bool IsActivate { get; set; }

    public byte Severity { get; set; }

    public string DefaultAction { get; set; }

    public DateTime UpdatedAt { get; set; }
}