//載入FrontAwesome
//引入一個工具來自動觀察 DOM(不改動i標籤)
import { library, dom } from '@fortawesome/fontawesome-svg-core'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'
//加入FrontAwesome特定圖示
import {
  faAnglesDown,
  faAnglesLeft,
  faAnglesRight,
  faAnglesUp,
  faBicycle,
  faBus,
  faCalendarAlt,
  faCalendarDays,
  faCamera,
  faCar,
  faClock,
  faComments,
  faFloppyDisk,
  faLink,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMapLocationDot,
  faMotorcycle,
  faPaperPlane as fasPaperPlane,
  faPersonWalking,
  faPhone,
  faPlus,
  faRotateRight,
  faShareNodes,
  faShip,
  faStore,
  faSuitcaseRolling,
  faTrain,
  faTrainSubway,
  faTrainTram,
  faUser,
  faWallet,
  faXmark,
  faYenSign,
} from '@fortawesome/free-solid-svg-icons'
import {
  faClock as farClock,
  faComment,
  faCopy,
  faPaperPlane,
  faPenToSquare,
} from '@fortawesome/free-regular-svg-icons'

dom.watch() // 這會自動將 <i> 標籤轉換為 <svg>

//加入FrontAwesome指定icon
library.add(
  faAnglesDown,
  faAnglesLeft,
  faAnglesRight,
  faAnglesUp,
  faBicycle,
  faBus,
  faCalendarAlt,
  faCalendarDays,
  faCamera,
  faCar,
  faClock,
  faComment,
  faComments,
  faCopy,
  faFloppyDisk,
  faLink,
  faLocationDot,
  faLock,
  faMagnifyingGlass,
  faMapLocationDot,
  faMotorcycle,
  fasPaperPlane,
  faPaperPlane,
  faPenToSquare,
  faPersonWalking,
  faPhone,
  faPlus,
  faRotateRight,
  faShareNodes,
  faShip,
  faStore,
  faSuitcaseRolling,
  faTrain,
  faTrainSubway,
  faTrainTram,
  faUser,
  faWallet,
  faXmark,
  faYenSign,
  farClock,
)

export default FontAwesomeIcon
