// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Luiu.Models;

public partial class LuiuDbContext : DbContext
{
    public LuiuDbContext(DbContextOptions<LuiuDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<TAdminLog> TAdminLogs { get; set; }

    public virtual DbSet<TCategory> TCategories { get; set; }

    public virtual DbSet<TCollect> TCollects { get; set; }

    public virtual DbSet<TComment> TComments { get; set; }

    public virtual DbSet<TCommentLike> TCommentLikes { get; set; }

    public virtual DbSet<TEvent> TEvents { get; set; }

    public virtual DbSet<TEventRank> TEventRanks { get; set; }

    public virtual DbSet<TEventSpotRelation> TEventSpotRelations { get; set; }

    public virtual DbSet<TEventTagRelation> TEventTagRelations { get; set; }

    public virtual DbSet<TExpense> TExpenses { get; set; }

    public virtual DbSet<TExpensesSplit> TExpensesSplits { get; set; }

    public virtual DbSet<TFollow> TFollows { get; set; }

    public virtual DbSet<TLoginLog> TLoginLogs { get; set; }

    public virtual DbSet<TMember> TMembers { get; set; }

    public virtual DbSet<TMemory> TMemories { get; set; }

    public virtual DbSet<TMemoryDay> TMemoryDays { get; set; }

    public virtual DbSet<TMemoryPhoto> TMemoryPhotos { get; set; }

    public virtual DbSet<TMemoryStop> TMemoryStops { get; set; }

    public virtual DbSet<TOauthLogin> TOauthLogins { get; set; }

    public virtual DbSet<TPackingCategory> TPackingCategories { get; set; }

    public virtual DbSet<TPackingItem> TPackingItems { get; set; }

    public virtual DbSet<TPhoto> TPhotos { get; set; }

    public virtual DbSet<TPost> TPosts { get; set; }

    public virtual DbSet<TPostLike> TPostLikes { get; set; }

    public virtual DbSet<TPostTag> TPostTags { get; set; }

    public virtual DbSet<TReference> TReferences { get; set; }

    public virtual DbSet<TRegion> TRegions { get; set; }

    public virtual DbSet<TRegionRank> TRegionRanks { get; set; }

    public virtual DbSet<TReport> TReports { get; set; }

    public virtual DbSet<TRole> TRoles { get; set; }

    public virtual DbSet<TSpot> TSpots { get; set; }

    public virtual DbSet<TSpotMonthlySnap> TSpotMonthlySnaps { get; set; }

    public virtual DbSet<TSpotPhoto> TSpotPhotos { get; set; }

    public virtual DbSet<TSpotRank> TSpotRanks { get; set; }

    public virtual DbSet<TSpotTagRelation> TSpotTagRelations { get; set; }

    public virtual DbSet<TSpotType> TSpotTypes { get; set; }

    public virtual DbSet<TSpotTypeRelation> TSpotTypeRelations { get; set; }

    public virtual DbSet<TSystemConfig> TSystemConfigs { get; set; }

    public virtual DbSet<TTag> TTags { get; set; }

    public virtual DbSet<TTrip> TTrips { get; set; }

    public virtual DbSet<TTripCollaborator> TTripCollaborators { get; set; }

    public virtual DbSet<TTripComment> TTripComments { get; set; }

    public virtual DbSet<TTripDetail> TTripDetails { get; set; }

    public virtual DbSet<TTripMember> TTripMembers { get; set; }

    public virtual DbSet<TTripSuggest> TTripSuggests { get; set; }

    public virtual DbSet<TType> TTypes { get; set; }

    public virtual DbSet<TUserPackingList> TUserPackingLists { get; set; }

    public virtual DbSet<TVerification> TVerifications { get; set; }

    public virtual DbSet<TViolationRule> TViolationRules { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<TAdminLog>(entity =>
        {
            entity.HasKey(e => e.ActionId).HasName("PK_AdminLogs");

            entity.ToTable("tAdminLogs");

            entity.Property(e => e.ActionId).HasColumnName("ActionID");
            entity.Property(e => e.ActionReason)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ActionTime)
                .HasDefaultValueSql("(getdate())", "DF_AdminLogs_ActionTime")
                .HasColumnType("datetime");
            entity.Property(e => e.ActionType)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.AdminId).HasColumnName("AdminID");
            entity.Property(e => e.IpAddress)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.PenaltyTime).HasColumnType("datetime");
            entity.Property(e => e.ReportId).HasColumnName("ReportID");
            entity.Property(e => e.TargetId).HasColumnName("TargetID");
            entity.Property(e => e.TargetType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__tCategor__19093A2B8142B2BB");

            entity.ToTable("tCategories");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TCollect>(entity =>
        {
            entity.HasKey(e => e.CollectId).HasName("PK_Collects");

            entity.ToTable("tCollects");

            entity.Property(e => e.CollectId).HasColumnName("CollectID");
            entity.Property(e => e.CollectTime).HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.ObjectId).HasColumnName("ObjectID");
            entity.Property(e => e.TypeId).HasColumnName("TypeID");
        });

        modelBuilder.Entity<TComment>(entity =>
        {
            entity.HasKey(e => e.CommentId).HasName("PK__tComment__C3B4DFAA80D7E86D");

            entity.ToTable("tComments");

            entity.Property(e => e.CommentId).HasColumnName("CommentID");
            entity.Property(e => e.CommentContent)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.CommentTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.PostId).HasColumnName("PostID");
        });

        modelBuilder.Entity<TCommentLike>(entity =>
        {
            entity.HasKey(e => e.CommentLikeId).HasName("PK__tComment__D36E159D513F6B03");

            entity.ToTable("tCommentLikes");

            entity.Property(e => e.CommentLikeId).HasColumnName("CommentLikeID");
            entity.Property(e => e.CommentId).HasColumnName("CommentID");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
        });

        modelBuilder.Entity<TEvent>(entity =>
        {
            entity.HasKey(e => e.EventId).HasName("PK_Event");

            entity.ToTable("tEvents");

            entity.Property(e => e.EventId).HasColumnName("EventID");
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("(getdate())", "DF_Event_CreateTime")
                .HasColumnType("datetime");
            entity.Property(e => e.EndTime).HasColumnType("datetime");
            entity.Property(e => e.EventName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.EventType).HasMaxLength(50);
            entity.Property(e => e.ImageBg).HasColumnName("ImageBG");
            entity.Property(e => e.OfficialUrl).HasColumnName("OfficialURL");
            entity.Property(e => e.StartTime).HasColumnType("datetime");
        });

        modelBuilder.Entity<TEventRank>(entity =>
        {
            entity.HasKey(e => e.EventRankId).HasName("PK_EventRank");

            entity.ToTable("tEventRanks");

            entity.Property(e => e.EventRankId).HasColumnName("EventRankID");
            entity.Property(e => e.EventId).HasColumnName("EventID");
            entity.Property(e => e.EventName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.RankDate)
                .HasDefaultValueSql("(getdate())", "DF_EventRank_RankDate")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TEventSpotRelation>(entity =>
        {
            entity.HasKey(e => new { e.EventId, e.SpotId }).HasName("PK_EventSpotRelation");

            entity.ToTable("tEventSpotRelations");

            entity.Property(e => e.EventId).HasColumnName("EventID");
            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
        });

        modelBuilder.Entity<TEventTagRelation>(entity =>
        {
            entity.HasKey(e => new { e.EventId, e.TagId }).HasName("PK_EventTagRelation");

            entity.ToTable("tEventTagRelations");

            entity.Property(e => e.EventId).HasColumnName("EventID");
            entity.Property(e => e.TagId).HasColumnName("TagID");
        });

        modelBuilder.Entity<TExpense>(entity =>
        {
            entity.HasKey(e => e.ExpenseId).HasName("PK__tExpense__1445CFF3DACB5A55");

            entity.ToTable("tExpenses");

            entity.Property(e => e.ExpenseId).HasColumnName("ExpenseID");
            entity.Property(e => e.MemoryId).HasColumnName("MemoryID");
            entity.Property(e => e.PayerUserId).HasColumnName("PayerUserID");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.TotalAmount).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<TExpensesSplit>(entity =>
        {
            entity.HasKey(e => e.SplitId).HasName("PK__tExpense__06CEF2D3F20593F8");

            entity.ToTable("tExpensesSplits");

            entity.Property(e => e.SplitId).HasColumnName("SplitID");
            entity.Property(e => e.DebtorUserId).HasColumnName("DebtorUserID");
            entity.Property(e => e.ExpenseId).HasColumnName("ExpenseID");
            entity.Property(e => e.OweAmount).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<TFollow>(entity =>
        {
            entity.HasKey(e => new { e.FollowerId, e.FollowingId }).HasName("PK_Follows");

            entity.ToTable("tFollows");

            entity.Property(e => e.FollowerId).HasColumnName("FollowerID");
            entity.Property(e => e.FollowingId).HasColumnName("FollowingID");
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("(getdate())", "DF_Follows_CreateTime")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TLoginLog>(entity =>
        {
            entity.HasKey(e => e.LoginId).HasName("PK_LoginLogs");

            entity.ToTable("tLoginLogs");

            entity.Property(e => e.LoginId).HasColumnName("LoginID");
            entity.Property(e => e.DeviceInfo).IsRequired();
            entity.Property(e => e.FailureReason)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Ipaddress)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("IPAddress");
            entity.Property(e => e.Location).HasMaxLength(100);
            entity.Property(e => e.LoginTime)
                .HasDefaultValueSql("(getdate())", "DF_LoginLogs_LoginTime")
                .HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.Status)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TMember>(entity =>
        {
            entity.HasKey(e => e.MemberId).HasName("PK_Members");

            entity.ToTable("tMembers");

            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.CreateDate)
                .HasDefaultValueSql("(getdate())", "DF_Members_CreateDate")
                .HasColumnType("datetime");
            entity.Property(e => e.DeleteTime).HasColumnType("datetime");
            entity.Property(e => e.Email)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.IconUrl)
                .HasMaxLength(255)
                .HasColumnName("IconURL");
            entity.Property(e => e.LockReason).HasMaxLength(50);
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Password)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.Phone)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.RoleId).HasColumnName("RoleID");
            entity.Property(e => e.UpdateDate)
                .HasDefaultValueSql("(getdate())", "DF_Members_UpdateDate")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId)
                .IsRequired()
                .HasMaxLength(30)
                .IsUnicode(false)
                .HasColumnName("UserID");
        });

        modelBuilder.Entity<TMemory>(entity =>
        {
            entity.HasKey(e => e.MemoryId).HasName("PK__tMemorie__9A4986B488DB5083");

            entity.ToTable("tMemories");

            entity.Property(e => e.MemoryId).HasColumnName("MemoryID");
            entity.Property(e => e.CoverImage).HasMaxLength(255);
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<TMemoryDay>(entity =>
        {
            entity.HasKey(e => e.DayId).HasName("PK__tMemoryD__BF3DD8258CDE6EF2");

            entity.ToTable("tMemoryDays");

            entity.Property(e => e.DayId).HasColumnName("DayID");
            entity.Property(e => e.MemoryId).HasColumnName("MemoryID");
        });

        modelBuilder.Entity<TMemoryPhoto>(entity =>
        {
            entity.HasKey(e => e.PhotoId).HasName("PK__tMemoryP__21B7B582093D02F5");

            entity.ToTable("tMemoryPhotos");

            entity.Property(e => e.PhotoId).HasColumnName("PhotoID");
            entity.Property(e => e.ImageUrl)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("ImageURL");
            entity.Property(e => e.StopId).HasColumnName("StopID");
        });

        modelBuilder.Entity<TMemoryStop>(entity =>
        {
            entity.HasKey(e => e.StopId).HasName("PK__tMemoryS__EB6A38D45515831E");

            entity.ToTable("tMemoryStops");

            entity.Property(e => e.StopId).HasColumnName("StopID");
            entity.Property(e => e.DayId).HasColumnName("DayID");
            entity.Property(e => e.Latitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(9, 6)");
            entity.Property(e => e.PlaceName)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.VideoEmbedUrl)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("VideoEmbedURL");
        });

        modelBuilder.Entity<TOauthLogin>(entity =>
        {
            entity.HasKey(e => new { e.AuthType, e.ProviderKey }).HasName("PK_OAuthLogin");

            entity.ToTable("tOAuthLogins");

            entity.Property(e => e.AuthType)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.ProviderKey).HasMaxLength(255);
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("(getdate())", "DF_OAuthLogin_CreateTime")
                .HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.ProviderDisplayName)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TPackingCategory>(entity =>
        {
            entity.HasKey(e => e.CategoryId).HasName("PK__tPacking__19093A2B67024C1C");

            entity.ToTable("tPackingCategories");

            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CategoryName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ListId).HasColumnName("ListID");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TPackingItem>(entity =>
        {
            entity.HasKey(e => e.ItemId).HasName("PK__tPacking__727E83EB56FBD906");

            entity.ToTable("tPackingItems");

            entity.Property(e => e.ItemId).HasColumnName("ItemID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsCheck).HasDefaultValue(false);
            entity.Property(e => e.ItemName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TPhoto>(entity =>
        {
            entity.HasKey(e => e.PhotoId).HasName("PK__tPhotos__21B7B58219B76896");

            entity.ToTable("tPhotos");

            entity.Property(e => e.PhotoId).HasColumnName("PhotoID");
            entity.Property(e => e.CommentId).HasColumnName("CommentID");
            entity.Property(e => e.ImgSaveName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.PhotoAddTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.PostId).HasColumnName("PostID");
        });

        modelBuilder.Entity<TPost>(entity =>
        {
            entity.HasKey(e => e.PostId).HasName("PK__Posts__AA12603828164C07");

            entity.ToTable("tPosts");

            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.CategoryId).HasColumnName("CategoryID");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.PostContent)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.PostTime)
                .HasDefaultValueSql("(getdate())", "DF__Posts__PostTime__4AB81AF0")
                .HasColumnType("datetime");
            entity.Property(e => e.PostTitle)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.ReferenceId).HasColumnName("ReferenceID");
        });

        modelBuilder.Entity<TPostLike>(entity =>
        {
            entity.HasKey(e => e.PostLikeId).HasName("PK__tPostLik__4CF65C79A7554E7B");

            entity.ToTable("tPostLikes");

            entity.Property(e => e.PostLikeId).HasColumnName("PostLikeID");
            entity.Property(e => e.LikeTime)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.PostId).HasColumnName("PostID");
        });

        modelBuilder.Entity<TPostTag>(entity =>
        {
            entity.HasKey(e => e.PostTagId).HasName("PK__tPostTag__325724DD6D388CCD");

            entity.ToTable("tPostTags");

            entity.Property(e => e.PostTagId).HasColumnName("PostTagID");
            entity.Property(e => e.PostId).HasColumnName("PostID");
            entity.Property(e => e.TagId).HasColumnName("TagID");
        });

        modelBuilder.Entity<TReference>(entity =>
        {
            entity.HasKey(e => e.ReferenceId).HasName("PK__tReferen__E1A99A797A62FF50");

            entity.ToTable("tReferences");

            entity.Property(e => e.ReferenceId).HasColumnName("ReferenceID");
            entity.Property(e => e.ReferenceItemId).HasColumnName("ReferenceItemID");
            entity.Property(e => e.TypeId).HasColumnName("TypeID");
        });

        modelBuilder.Entity<TRegion>(entity =>
        {
            entity.HasKey(e => e.RegionId).HasName("PK_SpotRegion");

            entity.ToTable("tRegions");

            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.RegionName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TRegionRank>(entity =>
        {
            entity.HasKey(e => e.RegionRankId).HasName("PK_RegionRanks");

            entity.ToTable("tRegionRanks");

            entity.Property(e => e.RegionRankId).HasColumnName("RegionRankID");
            entity.Property(e => e.RankDate)
                .HasDefaultValueSql("(getdate())", "DF_RegionRank_RankDate")
                .HasColumnType("datetime");
            entity.Property(e => e.RankType).HasMaxLength(50);
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.RegionName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TReport>(entity =>
        {
            entity.HasKey(e => e.ReportId).HasName("PK_Reports");

            entity.ToTable("tReports");

            entity.Property(e => e.ReportId)
                .ValueGeneratedNever()
                .HasColumnName("ReportID");
            entity.Property(e => e.CreateTime)
                .HasDefaultValueSql("(getdate())", "DF_Reports_CreateTime")
                .HasColumnType("datetime");
            entity.Property(e => e.ReportReson)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.ReporterId).HasColumnName("ReporterID");
            entity.Property(e => e.RuleId).HasColumnName("RuleID");
            entity.Property(e => e.TargetId).HasColumnName("TargetID");
            entity.Property(e => e.TargetType)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TRole>(entity =>
        {
            entity.HasKey(e => e.RoleId).HasName("PK_Role");

            entity.ToTable("tRole");

            entity.Property(e => e.RoleId)
                .ValueGeneratedNever()
                .HasColumnName("RoleID");
            entity.Property(e => e.RoleName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<TSpot>(entity =>
        {
            entity.HasKey(e => e.SpotId).HasName("PK_Spot");

            entity.ToTable("tSpots");

            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.GoogleMapId).HasColumnName("GoogleMapID");
            entity.Property(e => e.GoogleMapUrl).HasColumnName("GoogleMapURL");
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.Latitude).HasColumnType("decimal(10, 8)");
            entity.Property(e => e.Longitude).HasColumnType("decimal(11, 8)");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.OfficialUrl).HasColumnName("OfficialURL");
            entity.Property(e => e.PriceLevel).HasMaxLength(50);
            entity.Property(e => e.Rating).HasColumnType("decimal(2, 1)");
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.SpotName)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.Tel).HasMaxLength(50);
        });

        modelBuilder.Entity<TSpotMonthlySnap>(entity =>
        {
            entity.HasKey(e => e.SnapId).HasName("PK_SpotMonthlySnap");

            entity.ToTable("tSpotMonthlySnaps");

            entity.Property(e => e.SnapId).HasColumnName("SnapID");
            entity.Property(e => e.RegionId).HasColumnName("RegionID");
            entity.Property(e => e.SnapTime)
                .HasDefaultValueSql("(getdate())", "DF_SpotMonthlySnap_SnapTime")
                .HasColumnType("datetime");
            entity.Property(e => e.SpotId).HasColumnName("SpotID");
        });

        modelBuilder.Entity<TSpotPhoto>(entity =>
        {
            entity.HasKey(e => e.PhotoId).HasName("PK_SpotPhoto");

            entity.ToTable("tSpotPhotos");

            entity.Property(e => e.PhotoId).HasColumnName("PhotoID");
            entity.Property(e => e.PhotoUrl).HasColumnName("PhotoURL");
            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.UploadTime)
                .HasDefaultValueSql("(getdate())", "DF_SpotPhoto_UploadTime")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TSpotRank>(entity =>
        {
            entity.HasKey(e => e.SpotRankId).HasName("PK_SpotRank");

            entity.ToTable("tSpotRanks");

            entity.Property(e => e.SpotRankId).HasColumnName("SpotRankID");
            entity.Property(e => e.RankDate)
                .HasDefaultValueSql("(getdate())", "DF_SpotRank_RankDate")
                .HasColumnType("datetime");
            entity.Property(e => e.RankType).HasMaxLength(50);
            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.SpotName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TSpotTagRelation>(entity =>
        {
            entity.HasKey(e => new { e.SpotId, e.SpotTagId }).HasName("PK_SpotTagRelation");

            entity.ToTable("tSpotTagRelations");

            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.SpotTagId).HasColumnName("SpotTagID");
        });

        modelBuilder.Entity<TSpotType>(entity =>
        {
            entity.HasKey(e => e.TypeId).HasName("PK_SpotType_1");

            entity.ToTable("tSpotTypes");

            entity.Property(e => e.TypeId).HasColumnName("TypeID");
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TSpotTypeRelation>(entity =>
        {
            entity.HasKey(e => new { e.SpotId, e.TypeId }).HasName("PK_SpotType");

            entity.ToTable("tSpotTypeRelations");

            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.TypeId).HasColumnName("TypeID");
        });

        modelBuilder.Entity<TSystemConfig>(entity =>
        {
            entity.HasKey(e => e.ConfigKey).HasName("PK_SystemConfig");

            entity.ToTable("tSystemConfigs");

            entity.Property(e => e.ConfigKey).HasMaxLength(50);
            entity.Property(e => e.LastUpdated)
                .HasDefaultValueSql("(getdate())", "DF_SystemConfig_LastUpdated")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TTag>(entity =>
        {
            entity.HasKey(e => e.TagId).HasName("PK__tTags__657CFA4C74EAB4D5");

            entity.ToTable("tTags");

            entity.Property(e => e.TagId).HasColumnName("TagID");
            entity.Property(e => e.TagName)
                .IsRequired()
                .HasMaxLength(50);
        });

        modelBuilder.Entity<TTrip>(entity =>
        {
            entity.HasKey(e => e.TripId).HasName("PK__tTrips__51DC711E5813A5D5");

            entity.ToTable("tTrips");

            entity.Property(e => e.TripId).HasColumnName("TripID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsSuggest).HasDefaultValue(false);
            entity.Property(e => e.ListId).HasColumnName("ListID");
            entity.Property(e => e.OwnerId).HasColumnName("OwnerID");
            entity.Property(e => e.PrivacyStatus).HasDefaultValue((byte)0);
            entity.Property(e => e.ShortCode).HasMaxLength(8);
            entity.Property(e => e.TripGuid).HasDefaultValueSql("(newid())");
            entity.Property(e => e.TripName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
        });

        modelBuilder.Entity<TTripCollaborator>(entity =>
        {
            entity.HasKey(e => e.CollaboratorId).HasName("PK__tTripCol__3AC201C3AED3A892");

            entity.ToTable("tTripCollaborators");

            entity.Property(e => e.CollaboratorId).HasColumnName("CollaboratorID");
            entity.Property(e => e.Role).HasDefaultValue((byte)0);
            entity.Property(e => e.TripId).HasColumnName("TripID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<TTripComment>(entity =>
        {
            entity.HasKey(e => e.CommentId).HasName("PK__tTripCom__C3B4DFAA4DE0BF2D");

            entity.ToTable("tTripComments");

            entity.Property(e => e.CommentId).HasColumnName("CommentID");
            entity.Property(e => e.Content)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ParentId).HasColumnName("ParentID");
            entity.Property(e => e.TripId).HasColumnName("TripID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<TTripDetail>(entity =>
        {
            entity.HasKey(e => e.DetailId).HasName("PK__tTripDet__135C314D35314449");

            entity.ToTable("tTripDetails");

            entity.Property(e => e.DetailId).HasColumnName("DetailID");
            entity.Property(e => e.Budget).HasColumnType("decimal(18, 2)");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsMaster).HasDefaultValue(false);
            entity.Property(e => e.Notes).HasMaxLength(50);
            entity.Property(e => e.SpotAlias).HasMaxLength(20);
            entity.Property(e => e.SpotId).HasColumnName("SpotID");
            entity.Property(e => e.StayDuration).HasDefaultValue((short)60);
            entity.Property(e => e.TripId).HasColumnName("TripID");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.VersionId)
                .HasDefaultValue((byte)0)
                .HasColumnName("VersionID");
        });

        modelBuilder.Entity<TTripMember>(entity =>
        {
            entity.HasKey(e => new { e.MemberId, e.UserId }).HasName("PK__tTripMem__DD88C7F287424F22");

            entity.ToTable("tTripMembers");

            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<TTripSuggest>(entity =>
        {
            entity.HasKey(e => e.SuggesterId).HasName("PK__tTripSug__DA0E057B23AF98D0");

            entity.ToTable("tTripSuggests");

            entity.Property(e => e.SuggesterId).HasColumnName("SuggesterID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.IsApproved).HasDefaultValue(false);
            entity.Property(e => e.SuggestByUserId).HasColumnName("SuggestByUserID");
            entity.Property(e => e.Summary).HasMaxLength(100);
            entity.Property(e => e.TripId).HasColumnName("TripID");
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.VersionName)
                .IsRequired()
                .HasMaxLength(10);
        });

        modelBuilder.Entity<TType>(entity =>
        {
            entity.HasKey(e => e.TypeId).HasName("PK_Types");

            entity.ToTable("tTypes");

            entity.Property(e => e.TypeId).HasColumnName("TypeID");
            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasMaxLength(20);
        });

        modelBuilder.Entity<TUserPackingList>(entity =>
        {
            entity.HasKey(e => e.ListId).HasName("PK__tUserPac__E383286535C572EC");

            entity.ToTable("tUserPackingLists");

            entity.Property(e => e.ListId).HasColumnName("ListID");
            entity.Property(e => e.CreateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.ListName)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.UpdateAt)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime");
            entity.Property(e => e.UserId).HasColumnName("UserID");
        });

        modelBuilder.Entity<TVerification>(entity =>
        {
            entity.HasKey(e => e.Mvid).HasName("PK_Verification");

            entity.ToTable("tVerifications");

            entity.Property(e => e.Mvid).HasColumnName("MVID");
            entity.Property(e => e.CreatedAt)
                .HasDefaultValueSql("(getdate())", "DF_Verification_CreatedAt")
                .HasColumnType("datetime");
            entity.Property(e => e.ExpiryDate).HasColumnType("datetime");
            entity.Property(e => e.MemberId).HasColumnName("MemberID");
            entity.Property(e => e.RequestIp)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("RequestIP");
            entity.Property(e => e.TokenHash)
                .IsRequired()
                .HasMaxLength(128)
                .IsUnicode(false);
        });

        modelBuilder.Entity<TViolationRule>(entity =>
        {
            entity.HasKey(e => e.RuleId).HasName("PK_ViolationRules");

            entity.ToTable("tViolationRules");

            entity.Property(e => e.RuleId).HasColumnName("RuleID");
            entity.Property(e => e.DefaultAction).HasMaxLength(50);
            entity.Property(e => e.Description)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.IsActivate).HasDefaultValue(true, "DF__Violation__IsAct__793DFFAF");
            entity.Property(e => e.RuleType)
                .IsRequired()
                .HasMaxLength(10);
            entity.Property(e => e.Severity).HasDefaultValue((byte)3, "DF__Violation__Sever__7A3223E8");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.UpdatedAt)
                .HasDefaultValueSql("(getdate())", "DF__Violation__Updat__7B264821")
                .HasColumnType("datetime");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
