// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TAdminLog
{
    public int ActionId { get; set; }

    public string ActionType { get; set; }

    public string ActionReason { get; set; }

    public string IpAddress { get; set; }

    public DateTime ActionTime { get; set; }

    public DateTime PenaltyTime { get; set; }

    public string TargetType { get; set; }

    public int TargetId { get; set; }

    public int AdminId { get; set; }

    public int? ReportId { get; set; }
}