// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TCollect
{
    public int CollectId { get; set; }

    public int MemberId { get; set; }

    public int TypeId { get; set; }

    public int ObjectId { get; set; }

    public DateTime CollectTime { get; set; }
}