// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TCommentLike
{
    public int CommentLikeId { get; set; }

    public int CommentId { get; set; }

    public int MemberId { get; set; }
}