// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TComment
{
    public int CommentId { get; set; }

    public string CommentContent { get; set; }

    public DateTime CommentTime { get; set; }

    public int? ParentId { get; set; }

    public int PostId { get; set; }

    public int MemberId { get; set; }

    public bool IsDelete { get; set; }
}