// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TEvent
{
    public int EventId { get; set; }

    public string EventName { get; set; }

    public string Description { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public string EventType { get; set; }

    public string ImageBg { get; set; }

    public string OfficialUrl { get; set; }

    public DateTime CreateTime { get; set; }

    public int ViewCount { get; set; }

    public int FavoriteCount { get; set; }

    public int PlanCount { get; set; }

    public int RecordCount { get; set; }

    public int RefCount { get; set; }
}