// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TEventTagRelation
{
    public int EventId { get; set; }

    public int TagId { get; set; }
}