// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TExpense
{
    public int ExpenseId { get; set; }

    public int MemoryId { get; set; }

    public int PayerUserId { get; set; }

    public string Title { get; set; }

    public decimal TotalAmount { get; set; }
}