// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TFollow
{
    public int FollowerId { get; set; }

    public int FollowingId { get; set; }

    public DateTime CreateTime { get; set; }
}