// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TMember
{
    public int MemberId { get; set; }

    public string UserId { get; set; }

    public string Email { get; set; }

    public string Password { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public DateOnly? Birthday { get; set; }

    public byte Gender { get; set; }

    public string IconUrl { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime UpdateDate { get; set; }

    public bool ProfileStatus { get; set; }

    public byte Status { get; set; }

    public string LockReason { get; set; }

    public bool IsDelete { get; set; }

    public DateTime? DeleteTime { get; set; }

    public int RoleId { get; set; }
}