// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TMemoryPhoto
{
    public int PhotoId { get; set; }

    public int StopId { get; set; }

    public string ImageUrl { get; set; }
}