// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TMemoryStop
{
    public int StopId { get; set; }

    public int DayId { get; set; }

    public string PlaceName { get; set; }

    public decimal Latitude { get; set; }

    public decimal Longitude { get; set; }

    public DateTime? ArrivalTime { get; set; }

    public string MemoryText { get; set; }

    public string VideoEmbedUrl { get; set; }

    public string Duration { get; set; }

    public decimal? Expense { get; set; }

    public int? Rating { get; set; }

    public string ImageUrls { get; set; }
}