// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TOauthLogin
{
    public string AuthType { get; set; }

    public string ProviderKey { get; set; }

    public DateTime CreateTime { get; set; }

    public string ProviderDisplayName { get; set; }

    public int MemberId { get; set; }
}