// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TPackingItem
{
    public int ItemId { get; set; }

    public string ItemName { get; set; }

    public bool? IsCheck { get; set; }

    public int CategoryId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }
}