// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TPhoto
{
    public int PhotoId { get; set; }

    public int? PostId { get; set; }

    public int? CommentId { get; set; }

    public string ImgSaveName { get; set; }

    public DateTime PhotoAddTime { get; set; }
}