// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TPostLike
{
    public int PostLikeId { get; set; }

    public int PostId { get; set; }

    public int MemberId { get; set; }

    public DateTime LikeTime { get; set; }
}