// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TRegionRank
{
    public int RegionRankId { get; set; }

    public int RegionId { get; set; }

    public string RegionName { get; set; }

    public string RankType { get; set; }

    public DateTime RankDate { get; set; }

    public int? Rank { get; set; }
}