// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TSpotTagRelation
{
    public int SpotId { get; set; }

    public int SpotTagId { get; set; }
}