// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TSpotMonthlySnap
{
    public long SnapId { get; set; }

    public int SpotId { get; set; }

    public int RegionId { get; set; }

    public int SnapYear { get; set; }

    public int SnapMonth { get; set; }

    public int ViewCount { get; set; }

    public int FavoriteCount { get; set; }

    public int PlanCount { get; set; }

    public int RecordCount { get; set; }

    public int RefCount { get; set; }

    public DateTime SnapTime { get; set; }
}