// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TSpot
{
    public int SpotId { get; set; }

    public int RegionId { get; set; }

    public int? MemberId { get; set; }

    public string SpotName { get; set; }

    public decimal? Longitude { get; set; }

    public decimal? Latitude { get; set; }

    public string Tel { get; set; }

    public string Address { get; set; }

    public string OfficialUrl { get; set; }

    public string OpeningHoursJson { get; set; }

    public DateTime LastUpdated { get; set; }

    public decimal? Rating { get; set; }

    public int? UserRatingCount { get; set; }

    public string GoogleMapUrl { get; set; }

    public string GoogleMapId { get; set; }

    public string PriceLevel { get; set; }

    public int ViewCount { get; set; }

    public int FavoriteCount { get; set; }

    public int PlanCount { get; set; }

    public int RecordCount { get; set; }

    public int RefCount { get; set; }
}