// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TSpotRank
{
    public int SpotRankId { get; set; }

    public int SpotId { get; set; }

    public string SpotName { get; set; }

    public string RankType { get; set; }

    public DateTime RankDate { get; set; }

    public int? Rank { get; set; }
}