// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TSpotPhoto
{
    public int PhotoId { get; set; }

    public int SpotId { get; set; }

    public DateTime UploadTime { get; set; }

    public string PhotoUrl { get; set; }

    public int? Width { get; set; }

    public int? Height { get; set; }

    public bool Approved { get; set; }
}