// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TTripComment
{
    public int CommentId { get; set; }

    public string Content { get; set; }

    public DateTime CreateAt { get; set; }

    public int? ParentId { get; set; }

    public int TripId { get; set; }

    public int UserId { get; set; }

    public bool IsDeleted { get; set; }
}