// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TTripSuggest
{
    public int SuggesterId { get; set; }

    public string VersionName { get; set; }

    public string Summary { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }

    public bool? IsApproved { get; set; }

    public int SuggestByUserId { get; set; }

    public int TripId { get; set; }

    public bool IsDeleted { get; set; }
}