// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TTripDetail
{
    public int DetailId { get; set; }

    public string SpotAlias { get; set; }

    public string Notes { get; set; }

    public byte DayNumber { get; set; }

    public byte SortOrder { get; set; }

    public TimeOnly? ArrivalTime { get; set; }

    public short? StayDuration { get; set; }

    public byte? TransportMode { get; set; }

    public short? TransportTime { get; set; }

    public decimal? Budget { get; set; }

    public int TripId { get; set; }

    public int SpotId { get; set; }

    public byte? VersionId { get; set; }

    public bool? IsMaster { get; set; }

    public int? SuggestBy { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }
}
