// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Luiu.Models;

public partial class TUserPackingList
{
    public int ListId { get; set; }

    public string ListName { get; set; }

    public int UserId { get; set; }

    public bool IsDeleted { get; set; }

    public DateTime CreateAt { get; set; }

    public DateTime? UpdateAt { get; set; }
}