SET IDENTITY_INSERT [dbo].[tPackingItems] ON 

INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (1, N'發熱衣', 1, 1, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (2, N'休閒褲', 0, 1, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (3, N'睡衣', 1, 2, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (4, N'牙刷', 1, 3, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (5, N'洗面乳', 0, 3, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (6, N'行動電源', 1, 5, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (7, N'筆電充電器', 1, 6, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (8, N'相機電池', 1, 9, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (9, N'記憶卡', 1, 9, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (10, N'身分證', 1, 7, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (11, N'護照', 0, 7, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (12, N'防曬乳', 1, 10, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (13, N'雨衣', 0, 10, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (14, N'睡墊', 1, 11, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (15, N'卡式爐', 0, 11, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (16, N'短袖上衣', 1, 13, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (17, N'遮陽帽', 0, 13, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (18, N'厚外套', 1, 14, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (19, N'圍巾', 0, 14, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (20, N'錢包', 1, 15, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (21, N'鑰匙', 1, 15, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (22, N'感冒藥', 1, 4, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (23, N'尿布', 1, 4, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (24, N'登山杖', 0, 12, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (25, N'指北針', 1, 12, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (26, N'滑鼠', 1, 6, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (27, N'相機腳架', 0, 9, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (28, N'衛生紙', 1, 8, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (29, N'悠遊卡', 1, 8, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (30, N'平板電腦', 0, 5, 0, GETDATE(), GETDATE())
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (31, N'上衣三件', 1, 16, 0, CAST(N'2026-05-27T10:37:44.133' AS DateTime), CAST(N'2026-05-27T13:36:34.507' AS DateTime))
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (32, N'褲子三件', 0, 16, 0, CAST(N'2026-05-27T10:37:58.547' AS DateTime), CAST(N'2026-05-27T10:37:58.547' AS DateTime))
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (33, N'襪子兩雙', 0, 16, 0, CAST(N'2026-05-27T10:38:04.753' AS DateTime), CAST(N'2026-05-27T10:38:04.753' AS DateTime))
INSERT [dbo].[tPackingItems] ([ItemID], [ItemName], [IsCheck], [CategoryID], [IsDeleted], [CreateAt], [UpdateAt]) VALUES (34, N'拖鞋一雙', 0, 16, 0, CAST(N'2026-05-27T10:38:11.670' AS DateTime), CAST(N'2026-05-27T10:38:11.670' AS DateTime))
SET IDENTITY_INSERT [dbo].[tPackingItems] OFF
GO
